sudo: required
language: bash
before_deploy:
- eval "($ssh-agent -s)"
- mkdir -p ~/.ssh && echo "Host *" > ~/.ssh/config && echo " StrictHostKeyChecking
  no" >> ~/.ssh/config
- chmod 600 home.pem
deploy:
  provider: script
  skip_cleanup: true
  script: ssh -i home.pem ubuntu@ec2-18-223-151-157.us-east-2.compute.amazonaws.com
    'docker-compose --version'
  on:
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_9e6a438b5ac7_key -iv $encrypted_9e6a438b5ac7_iv
  -in home.pem.enc -out home.pem -d
